// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Logs;

public partial class Logs
{
    public long Id { get; set; }

    public string Type { get; set; }

    public string Subtype { get; set; }

    public short? Loglevel { get; set; }

    public string Message { get; set; }

    public string Innermessage { get; set; }

    public string Component { get; set; }

    public DateTime Date { get; set; }
}