// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DAOLayer.Net7.Logs;

public partial class LogsContext : DbContext
{
    public LogsContext()
    {
    }

    public LogsContext(DbContextOptions<LogsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Logs> Logs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Logs>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Component)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("component");
            entity.Property(e => e.Date)
                .HasColumnType("datetime")
                .HasColumnName("date");
            entity.Property(e => e.Innermessage).HasColumnName("innermessage");
            entity.Property(e => e.Loglevel).HasColumnName("loglevel");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.Subtype)
                .HasMaxLength(30)
                .IsFixedLength()
                .HasColumnName("subtype");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(30)
                .IsFixedLength()
                .HasColumnName("type");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}