// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class Country
{
    public long Id { get; set; }

    public string Name { get; set; }

    public short? AreaCode { get; set; }

    public DateTimeOffset? TimeOffset { get; set; }

    public virtual ICollection<NdsSupplementCustomerInventory> NdsSupplementCustomerInventory { get; set; } = new List<NdsSupplementCustomerInventory>();

    public virtual ICollection<NdsSupplementLegalStatus> NdsSupplementLegalStatus { get; set; } = new List<NdsSupplementLegalStatus>();
}