// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementLegalStatusTypes
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string HelpText { get; set; }

    public virtual ICollection<NdsSupplementLegalStatus> NdsSupplementLegalStatus { get; set; } = new List<NdsSupplementLegalStatus>();
}