// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementSchedulePerDate
{
    public long Id { get; set; }

    public long CustomerId { get; set; }

    public DateTime Date { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<NdsSupplementSchedule> NdsSupplementSchedule { get; set; } = new List<NdsSupplementSchedule>();
}