// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementScheduleDose
{
    public long Id { get; set; }

    public long FkSupplementSchedule { get; set; }

    public double UnitCountTarget { get; set; }

    public DateTime? ScheduledTime { get; set; }

    public double? UnitCountActual { get; set; }

    public bool IsSkipped { get; set; }

    public bool IsComplete { get; set; }

    public DateTime? CompletionTime { get; set; }

    public DateTimeOffset? CompletionTimeOffset { get; set; }

    public string Remarks { get; set; }

    public long? SupplementSkipReason { get; set; }

    public string SupplementSkipOtherReason { get; set; }

    public bool? IsSnoozed { get; set; }

    public DateTime? SnoozedTime { get; set; }

    public virtual NdsSupplementSchedule FkSupplementScheduleNavigation { get; set; }

    public virtual NdsSupplementSkipReason SupplementSkipReasonNavigation { get; set; }
}