// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementInstruction
{
    public long Id { get; set; }

    public string Description { get; set; }

    public bool RequiresSourceOfFat { get; set; }

    public bool TakeAfterMeal { get; set; }

    public bool TakeBeforeSleep { get; set; }

    public bool TakeOnEmptyStomach { get; set; }

    public virtual ICollection<NdsSupplementReference> NdsSupplementReference { get; set; } = new List<NdsSupplementReference>();
}