// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementSkipReason
{
    public long Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<NdsSupplementScheduleDose> NdsSupplementScheduleDose { get; set; } = new List<NdsSupplementScheduleDose>();
}