// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementPlanDose
{
    public long Id { get; set; }

    public long FkSupplementPlanSupplement { get; set; }

    public double UnitCount { get; set; }

    public TimeSpan ScheduledTime { get; set; }

    public string Remark { get; set; }

    public double? DoseWarningLimit { get; set; }

    public double? DoseHardCeilingLimit { get; set; }

    public virtual NdsSupplementPlanSupplement FkSupplementPlanSupplementNavigation { get; set; }
}