// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementCustomerInventory
{
    public long Id { get; set; }

    public long FkCustomerId { get; set; }

    public long FkSupplementReference { get; set; }

    public double? UnitsLeft { get; set; }

    public virtual Country FkCustomer { get; set; }

    public virtual NdsSupplementReference FkSupplementReferenceNavigation { get; set; }
}