// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementSchedule
{
    public long Id { get; set; }

    public long FkSupplementSchedulePerDate { get; set; }

    public long FkSupplementReference { get; set; }

    public bool? IsCustomerCreatedEntry { get; set; }

    public bool? IsFreeEntry { get; set; }

    public string FreeEntryName { get; set; }

    public long? FkFreeEntryUnitMetric { get; set; }

    public string FreeEntryInstructions { get; set; }

    public bool? IsSnoozed { get; set; }

    public DateTime? SnoozedTime { get; set; }

    public virtual NdsSupplementReference FkSupplementReferenceNavigation { get; set; }

    public virtual NdsSupplementSchedulePerDate FkSupplementSchedulePerDateNavigation { get; set; }

    public virtual ICollection<NdsSupplementScheduleDose> NdsSupplementScheduleDose { get; set; } = new List<NdsSupplementScheduleDose>();
}