// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementPlanWeekly
{
    public long Id { get; set; }

    public long FkCustomerId { get; set; }

    public DateTime? ActiveSince { get; set; }

    public bool IsActive { get; set; }

    public string Remark { get; set; }

    public DateTime? InactiveSince { get; set; }

    public virtual User FkCustomer { get; set; }

    public virtual ICollection<NdsSupplementPlanDaily> NdsSupplementPlanDaily { get; set; } = new List<NdsSupplementPlanDaily>();
}