// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementLegalStatus
{
    public long Id { get; set; }

    public long FkSupplementReference { get; set; }

    public long FkCountryId { get; set; }

    public long FkSupplementLegalStatusTypes { get; set; }

    public string SpecialDisclaimer { get; set; }

    public string Remarks { get; set; }

    public string LegalReferenceUrl { get; set; }

    public virtual Country FkCountry { get; set; }

    public virtual NdsSupplementLegalStatusTypes FkSupplementLegalStatusTypesNavigation { get; set; }

    public virtual NdsSupplementReference FkSupplementReferenceNavigation { get; set; }
}