// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementPlanSupplement
{
    public long Id { get; set; }

    public long FkSupplementPlanDaily { get; set; }

    public long FkSupplementReference { get; set; }

    public bool IsCustomerCreatedEntry { get; set; }

    public bool IsFreeEntry { get; set; }

    public string FreeEntryName { get; set; }

    public long? FkFreeEntryUnitMetric { get; set; }

    public string Remark { get; set; }

    public long? FkReferenceToTrainer { get; set; }

    public virtual NdsSupplementPlanDaily FkSupplementPlanDailyNavigation { get; set; }

    public virtual NdsSupplementReference FkSupplementReferenceNavigation { get; set; }

    public virtual ICollection<NdsSupplementPlanDose> NdsSupplementPlanDose { get; set; } = new List<NdsSupplementPlanDose>();
}