// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsSupplementPlanDaily
{
    public long Id { get; set; }

    public long FkSupplementPlanWeekly { get; set; }

    /// <summary>
    /// start at 0 = Monday 
    /// </summary>
    public short DayOfWeek { get; set; }

    public virtual NdsSupplementPlanWeekly FkSupplementPlanWeeklyNavigation { get; set; }

    public virtual ICollection<NdsSupplementPlanSupplement> NdsSupplementPlanSupplement { get; set; } = new List<NdsSupplementPlanSupplement>();
}