// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsTemplateSupplementPlanDose
{
    public long Id { get; set; }

    public long FkTemplateSupplementPlanSupplement { get; set; }

    public double UnitCount { get; set; }

    public DateTime SceduledTime { get; set; }

    public virtual NdsTemplateSupplementPlanSupplement FkTemplateSupplementPlanSupplementNavigation { get; set; }
}