// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsTemplateSupplementPlanDaily
{
    public long Id { get; set; }

    /// <summary>
    /// start at 0 = monday
    /// </summary>
    public short DayOfWeek { get; set; }

    public long FkTemplateSupplementPlanWeeklyId { get; set; }

    public virtual NdsTemplateSupplementPlanWeekly FkTemplateSupplementPlanWeekly { get; set; }

    public virtual ICollection<NdsTemplateSupplementPlanSupplement> NdsTemplateSupplementPlanSupplement { get; set; } = new List<NdsTemplateSupplementPlanSupplement>();
}