// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsTemplateSupplementPlanWeekly
{
    public long Id { get; set; }

    public string Name { get; set; }

    public DateTime ActiveSince { get; set; }

    public DateTime DeletedSince { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<NdsTemplateSupplementPlanDaily> NdsTemplateSupplementPlanDaily { get; set; } = new List<NdsTemplateSupplementPlanDaily>();
}