// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Supplement;

public partial class NdsTemplateSupplementPlanSupplement
{
    public long Id { get; set; }

    public long FkTemplateSupplementPlanDaily { get; set; }

    public long FkSupplementReference { get; set; }

    public bool IsCustomerCreatedEntry { get; set; }

    public bool IsFreeEntry { get; set; }

    public string FreeEntryName { get; set; }

    public long? FkFreeEntryUnitMetric { get; set; }

    public virtual NdsTemplateSupplementPlanDaily FkTemplateSupplementPlanDailyNavigation { get; set; }

    public virtual ICollection<NdsTemplateSupplementPlanDose> NdsTemplateSupplementPlanDose { get; set; } = new List<NdsTemplateSupplementPlanDose>();
}