// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Exercise;

public partial class EdsExercise
{
    public long Id { get; set; }

    public long FkTrainingId { get; set; }

    public long FkExerciseTypeId { get; set; }

    public bool IsSkipped { get; set; }

    public bool IsComplete { get; set; }

    public DateTime? EndTimeStamp { get; set; }

    public bool IsCustomerAddedExercise { get; set; }

    public DateTimeOffset? TimeOffset { get; set; }

    public virtual ICollection<EdsSet> EdsSet { get; set; } = new List<EdsSet>();

    public virtual EdsExerciseType FkExerciseType { get; set; }

    public virtual EdsTrainingSession FkTraining { get; set; }
}