// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Exercise;

public partial class EdsExerciseTypeUserHistory
{
    public long UserId { get; set; }

    public long FkExerciseTypeId { get; set; }

    public long Id { get; set; }

    public virtual ICollection<EdsExerciseTypeUserHistorySetHistory> EdsExerciseTypeUserHistorySetHistory { get; set; } = new List<EdsExerciseTypeUserHistorySetHistory>();
}