// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Exercise;

public partial class EdsReasonForReschedule
{
    public long Id { get; set; }

    public string Name { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<EdsTrainingSession> EdsTrainingSession { get; set; } = new List<EdsTrainingSession>();
}