// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.User;

public partial class Address
{
    public long Id { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressCity { get; set; }

    public string AddressState { get; set; }

    public string AddressPostalCode { get; set; }

    public string AddressCountry { get; set; }

    public virtual ICollection<User> User { get; set; } = new List<User>();
}