// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.User;

public partial class Apn
{
    public long Id { get; set; }

    public long FkUserId { get; set; }

    public string DeviceId { get; set; }

    public bool? IsActive { get; set; }

    public virtual User FkUser { get; set; }
}