// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.User;

public partial class ApnErrorLog
{
    public long Id { get; set; }

    public long? FkUsrId { get; set; }

    public string Message { get; set; }

    public string Stack { get; set; }

    public DateTime Timestamp { get; set; }
}