// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.User;

public partial class ApnLogs
{
    public long Id { get; set; }

    public long FkUserId { get; set; }

    public string Platform { get; set; }

    public string Devicekey { get; set; }

    public string Category { get; set; }

    public string Title { get; set; }

    public DateTime Timestamp { get; set; }
}