// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.User;

public partial class ApnSchedule
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public string Message { get; set; }

    public bool HasSent { get; set; }

    public DateTime DateToTriggerUtc { get; set; }

    public DateTime CreatedUtc { get; set; }

    public long ItemId { get; set; }

    public string DeviceId { get; set; }

    public string Category { get; set; }

    public string Platform { get; set; }
}