// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.User;

public partial class QtoolConnect
{
    public long Id { get; set; }

    public Guid UrlKey { get; set; }

    public string Value { get; set; }

    public bool IsActive { get; set; }

    public DateTime ExpiresUtc { get; set; }

    public long FkUserId { get; set; }

    public bool Complete { get; set; }
}