// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.User;

public partial class UGenericQuestions
{
    public long Id { get; set; }

    public string QuestionName { get; set; }

    public string QuestionText { get; set; }

    public string QuestionAnswer { get; set; }

    public long FkUserId { get; set; }

    public virtual User FkUser { get; set; }
}