// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataEntryTest.Models;

public partial class Eds12weekPlan
{
    public long Id { get; set; }

    public string Name { get; set; }

    public bool IsTemplate { get; set; }

    public bool IsCurrent { get; set; }

    public short DurationWeeks { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public long? FkCustomerId { get; set; }

    public virtual ICollection<EdsWeeklyPlan> EdsWeeklyPlan { get; } = new List<EdsWeeklyPlan>();

    public virtual User FkCustomer { get; set; }
}