// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitAppData.Net7;

public partial class EdsDailyPlan
{
    public long Id { get; set; }

    public long FkEdsWeeklyPlanId { get; set; }

    public DateTime? StartDay { get; set; }

    public DateTime? EndDay { get; set; }

    public bool IsComplete { get; set; }

    public virtual ICollection<EdsTrainingSession> EdsTrainingSession { get; } = new List<EdsTrainingSession>();

    public virtual EdsWeeklyPlan FkEdsWeeklyPlan { get; set; }
}