// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitAppData.Net7;

public partial class EdsSetMetricTypes
{
    public long Id { get; set; }

    public string Name { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsRepetition { get; set; }

    public bool IsWeight { get; set; }

    public bool IsResistance { get; set; }

    public bool IsDistance { get; set; }

    public bool IsTime { get; set; }

    public virtual ICollection<EdsAvaiableSetMetrics> EdsAvaiableSetMetrics { get; } = new List<EdsAvaiableSetMetrics>();

    public virtual ICollection<EdsSetMetrics> EdsSetMetrics { get; } = new List<EdsSetMetrics>();

    public virtual ICollection<EdsSetMetricsDefault> EdsSetMetricsDefault { get; } = new List<EdsSetMetricsDefault>();
}