// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitAppData.Net7;

public partial class EdsSetMetricsDefault
{
    public long Id { get; set; }

    public long? FkSetDefaultsId { get; set; }

    public long? FkSetMetricTypeId { get; set; }

    public long? DefaultCustomMetric { get; set; }

    public virtual EdsSetDefaults FkSetDefaults { get; set; }

    public virtual EdsSetMetricTypes FkSetMetricType { get; set; }
}