// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitAppData.Net7;

public partial class EdsSetMetrics
{
    public long Id { get; set; }

    public long? FkSetId { get; set; }

    public long? FkMetricsTypeId { get; set; }

    public double? TargetCustomMetric { get; set; }

    public double? ActualCustomMetric { get; set; }

    public virtual EdsSetMetricTypes FkMetricsType { get; set; }

    public virtual EdsSet FkSet { get; set; }
}