// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitAppData.Net7;

public partial class EdsSetDefaults
{
    public long Id { get; set; }

    public long? FkExerciseTypeId { get; set; }

    public short SetSequenceNumber { get; set; }

    public virtual ICollection<EdsSetMetricsDefault> EdsSetMetricsDefault { get; } = new List<EdsSetMetricsDefault>();

    public virtual EdsExerciseType FkExerciseType { get; set; }
}