// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitAppData.Net7;

public partial class EdsTrainingSession
{
    public long Id { get; set; }

    public long FkEdsDailyPlan { get; set; }

    public string Name { get; set; }

    public DateTime? StartDateTime { get; set; }

    public DateTime? EndDateTime { get; set; }

    public bool IsMoved { get; set; }

    public bool IsSkipped { get; set; }

    public DateTime? EndTimeStamp { get; set; }

    public bool IsCustomerAddedTrainingSession { get; set; }

    public long? ReasonForReschedule { get; set; }

    public long? ReadonForSkipping { get; set; }

    public virtual ICollection<EdsExercise> EdsExercise { get; } = new List<EdsExercise>();

    public virtual EdsDailyPlan FkEdsDailyPlanNavigation { get; set; }
}