// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitAppData.Net7;

public partial class EdsWeeklyPlan
{
    public long Id { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public long FkEds12weekPlan { get; set; }

    public virtual ICollection<EdsDailyPlan> EdsDailyPlan { get; } = new List<EdsDailyPlan>();

    public virtual Eds12weekPlan FkEds12weekPlanNavigation { get; set; }
}