// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitAppData.Net7;

public partial class User
{
    public long Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public int UserLevel { get; set; }

    public long? FkFederatedUser { get; set; }

    public virtual ICollection<Eds12weekPlan> Eds12weekPlan { get; } = new List<Eds12weekPlan>();
}