// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Nutrition;

public partial class FnsMealType
{
    public long Id { get; set; }

    public string Name { get; set; }

    public bool HasTarget { get; set; }

    public bool IsDeleted { get; set; }

    public TimeSpan? Defaulttime { get; set; }

    public virtual ICollection<FnsNutritionActualMeal> FnsNutritionActualMeal { get; set; } = new List<FnsNutritionActualMeal>();
}