// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Nutrition;

public partial class FnsNutritionActualDish
{
    public long Id { get; set; }

    public long FkNutritionActualMealId { get; set; }

    public long FkDishTypeId { get; set; }

    public long? FkDishTranscriptionTypeId { get; set; }

    public bool IsComplete { get; set; }

    public bool IsError { get; set; }

    public bool IsFavorite { get; set; }

    public bool IsFrequent { get; set; }

    public DateTime CreationTimestamp { get; set; }

    public DateTime? ErrorTimestamp { get; set; }

    public long? FkErrorCodeId { get; set; }

    public DateTime? CompletionTimestamp { get; set; }

    public string Name { get; set; }

    public string Remarks { get; set; }

    public string TranscriberRemarks { get; set; }

    public double ShareOfDishConsumed { get; set; }

    public double NumberOfServingsConsumed { get; set; }

    public long? FkReuseReferenceId { get; set; }

    public string UploadPhotoReference { get; set; }

    public long? FkTranscriberId { get; set; }

    public long? FkUserRecipeId { get; set; }

    public double? CalorieActual { get; set; }

    public double? ProteinActual { get; set; }

    public double? CrabsActual { get; set; }

    public double? SugarActual { get; set; }

    public double? FatActual { get; set; }

    public double? UnsaturatedFatActual { get; set; }

    public double? FiberGramsActual { get; set; }

    public double? SaturatedFatGramsActual { get; set; }

    public double? AlcoholGramsActual { get; set; }

    public long? FkUserId { get; set; }

    public virtual FnsTranscriptionType FkDishTranscriptionType { get; set; }

    public virtual FmsDishType FkDishType { get; set; }

    public virtual FnsErrorCode FkErrorCode { get; set; }

    public virtual FnsNutritionActualMeal FkNutritionActualMeal { get; set; }

    public virtual FnsNutritionActualDish FkReuseReference { get; set; }

    public virtual User FkTranscriber { get; set; }

    public virtual User FkUser { get; set; }

    public virtual ICollection<FnsNutritionActualDish> InverseFkReuseReference { get; set; } = new List<FnsNutritionActualDish>();
}