// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Nutrition;

public partial class FnsTranscriptionType
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string ShortId { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<FnsNutritionActualDish> FnsNutritionActualDish { get; set; } = new List<FnsNutritionActualDish>();
}