// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Chat;

public partial class MsgBroadcast
{
    public long Id { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public string Url { get; set; }

    public string Icon { get; set; }

    public string Imageurl { get; set; }

    public DateTime Timestamp { get; set; }

    public long? FkUserId { get; set; }

    public bool IsDeleted { get; set; }
}