// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Chat;

public partial class MsgMessage
{
    public long Id { get; set; }

    public string MessageContent { get; set; }

    public DateTime Timestamp { get; set; }

    public long FkUserSender { get; set; }

    public long FkRoomId { get; set; }

    public virtual MsgRoom FkRoom { get; set; }

    public virtual User FkUserSenderNavigation { get; set; }
}