// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Chat;

public partial class UInternalNotes
{
    public long Id { get; set; }

    public DateTime? Date { get; set; }

    public long ByUser { get; set; }

    public string Note { get; set; }

    public long ForUser { get; set; }

    public virtual User ByUserNavigation { get; set; }

    public virtual User ForUserNavigation { get; set; }
}