// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAOLayer.Net7.Chat;

public partial class User
{
    public long Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public int UserLevel { get; set; }

    public string FkFederatedUser { get; set; }

    public DateTimeOffset? LastKnownTimeOffset { get; set; }

    public DateTimeOffset? SetTimeOffset { get; set; }

    public bool? IsActive { get; set; }

    public Guid? ApiKey { get; set; }

    public bool? IsNewBarcode { get; set; }

    public string BarcodeString { get; set; }

    public DateTime? Dob { get; set; }

    public int? Height { get; set; }

    public int? Weight { get; set; }

    public string Gender { get; set; }

    public string Country { get; set; }

    public long? FkInternalNotesId { get; set; }

    public long? FkGender { get; set; }

    public string MiddleName { get; set; }

    public string MobileCountryCode { get; set; }

    public long? FkShippingAddress { get; set; }

    public int Signupstatus { get; set; }

    public virtual ICollection<MsgMessage> MsgMessage { get; set; } = new List<MsgMessage>();
}